### ISSUE TITLE
Error while starting Keenetic Collector container

### ISSUE THREAD

**Issue by Andrewkha** [vitaliy-sk/keenetic-grafana-monitoring#23]
Hi!

Keenetic Collector container permanently restarts with the following messages in the log:

>   _  __                    _   _         _____      _ _           _             
> 
>  | |/ /                   | | (_)       / ____|    | | |         | |            
> 
>  | ' / ___  ___ _ __   ___| |_ _  ___  | |     ___ | | | ___  ___| |_ ___  _ __🇺🇦  🇺🇦  🇺🇦 
> 
>  |  < / _ \/ _ \ '_ \ / _ \ __| |/ __| | |    / _ \| | |/ _ \/ __| __/ _ \| '__|
> 
>  | . \  __/  __/ | | |  __/ |_| | (__  | |___| (_) | | |  __/ (__| || (_) | |   
> 
>  |_|\_\___|\___|_| |_|\___|\__|_|\___|  \_____\___/|_|_|\___|\___|\__\___/|_|   
> 
> Traceback (most recent call last):
> 
>   File "/home/keentic_influxdb_exporter.py", line 109, in <module>
> 
>     infuxdb_writer = InfuxWriter(config['influx2'], config_path)
> 
>   File "/usr/local/lib/python3.8/configparser.py", line 960, in __getitem__
> 
>     raise KeyError(key)
> 
> KeyError: 'influx2'

**Comment by Andrewkha** [comment]
Nevermind, my typo
