### ISSUE TITLE
Authentication error with new Keenetic OS

### ISSUE THREAD

**Issue by ilker-aktuna** [vitaliy-sk/keenetic-grafana-monitoring#25]
Hi,

I've recently updated my Keenetic router to version 4.2.1
Prior to that I had not tried Keenetic Grafana Monitoring. I am just trying this today.
Unfortunately, it seems that it can not authenticate.

I am sure that the router user/pass defined in config.ini is correct.
I don't know if this is an issue specific to new version (4.2.1) because this is my first attempt and my router is already 4.2.1 and there is no option to downgrade.

Admin endpoint is defined as:
admin_endpoint=http://127.0.0.1:80

I get the following error:
```

/opt/home/keenetic-grafana-monitoring # python /opt/home/keenetic-grafana-monitoring/keentic_influxdb_exporter.py
2024-11-02 16:48:02,630 - keentic_influxdb_exporter.py - INFO - 

  _  __                    _   _         _____      _ _           _             
 | |/ /                   | | (_)       / ____|    | | |         | |            
 | ' / ___  ___ _ __   ___| |_ _  ___  | |     ___ | | | ___  ___| |_ ___  _ __ðŸ‡ºðŸ‡¦  ðŸ‡ºðŸ‡¦  ðŸ‡ºðŸ‡¦ 
 |  < / _ \/ _ \ '_ \ / _ \ __| |/ __| | |    / _ \| | |/ _ \/ __| __/ _ \| '__|
 | . \  __/  __/ | | |  __/ |_| | (__  | |___| (_) | | |  __/ (__| || (_) | |   
 |_|\_\___|\___|_| |_|\___|\__|_|\___|  \_____\___/|_|_|\___|\___|\__\___/|_|   


2024-11-02 16:48:02,671 - influxdb_writter.py - INFO - Connecting to InfluxDB: http://192.168.254.20:8086
2024-11-02 16:48:02,673 - keentic_influxdb_exporter.py - INFO - Connecting to router: http://127.0.0.1:80
2024-11-02 16:48:02,678 - keentic_influxdb_exporter.py - INFO - Configuring metric: processes
2024-11-02 16:48:03,627 - keentic_influxdb_exporter.py - INFO - Configuring metric: interface
2024-11-02 16:48:03,978 - keentic_influxdb_exporter.py - INFO - Configuring metric: ip hotspot
2024-11-02 16:48:06,384 - keentic_influxdb_exporter.py - INFO - Configuring metric: interface
2024-11-02 16:48:08,233 - keentic_influxdb_exporter.py - INFO - Configuring metric: system
2024-11-02 16:48:09,987 - keentic_influxdb_exporter.py - INFO - Configuring metric: internet status
2024-11-02 16:48:11,034 - keentic_influxdb_exporter.py - INFO - Configuring metric: media
2024-11-02 16:48:12,064 - keentic_influxdb_exporter.py - INFO - Configuring metric: interface stat
2024-11-02 16:48:12,938 - keentic_influxdb_exporter.py - INFO - Configuring metric: interface stat
2024-11-02 16:48:13,813 - keentic_influxdb_exporter.py - INFO - Configuring metric: interface stat
2024-11-02 16:48:14,700 - keentic_influxdb_exporter.py - INFO - Configuring metric: interface stat
2024-11-02 16:48:15,578 - keentic_influxdb_exporter.py - INFO - Configuring metric: interface stat
2024-11-02 16:48:16,465 - keentic_influxdb_exporter.py - INFO - Configuration done. Start collecting with interval: 30 sec
Traceback (most recent call last):
  File "/opt/home/keenetic-grafana-monitoring/keentic_influxdb_exporter.py", line 125, in <module>
    metrics = collector.collect()
              ^^^^^^^^^^^^^^^^^^^
  File "/opt/home/keenetic-grafana-monitoring/keentic_influxdb_exporter.py", line 41, in collect
    response = self._keenetic_client.metric(self._command, self._params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/home/keenetic-grafana-monitoring/keenetic_api.py", line 45, in metric
    if self._auth():
       ^^^^^^^^^^^^
  File "/opt/home/keenetic-grafana-monitoring/keenetic_api.py", line 42, in _auth
    raise ConnectionError(f"Failed to check authorisation, status unknown ({check_auth_response.status_code})")
ConnectionError: Failed to check authorisation, status unknown (403)
/opt/home/keenetic-grafana-monitoring #
```

**Comment by ilker-aktuna** [comment]
I see that there is no response to issues within 2024.
is this project abandoned ?

**Comment by vitaliy-sk** [comment]
Nope project isn't abandoned 
You need to set router IP in admin_endpoint, `127.0.0.1` isn't valid router IP.

**Comment by ilker-aktuna** [comment]
ok it works if I use 192.168.1.1 
but in fact I run it on the router , so 127.0.0.1 should provide the same result.

now it works. but when I run 
"/opt/etc/init.d/S99keeneticgrafana start"
I don't see python in processes (ps output)
If I run :
python /opt/home/keenetic-grafana-monitoring/keentic_influxdb_exporter.py 
manually, then it collects data

why the start script does not work ?

**Comment by ilker-aktuna** [comment]
I think the data collection fails at some point. Sample dashboard is only filled partially in my case:
![image](https://github.com/user-attachments/assets/679b67de-4d7c-46ce-8e04-96c6590de700)

**Comment by ilker-aktuna** [comment]
I found the reason:

# nohup python /opt/home/keenetic-grafana-monitoring/keentic_influxdb_exporter.py
-sh: nohup: not found


how  can I add nohup to the shell ?

**Comment by ilker-aktuna** [comment]
even if I run the script manually (it runs and collects data) I never see panels filled.

**Comment by vitaliy-sk** [comment]
> how can I add nohup to the shell ?

Try to setup `coreutils` package via opkg

**Comment by ilker-aktuna** [comment]
~ # opkg install coreutils
Installing coreutils (9.3-1) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/coreutils_9.3-1_mipsel-3.4.ipk
Configuring coreutils.
~ # 
~ # 
~ # 
~ # nohup
-sh: nohup: not found
~ # 


Still no "nohup"

**Comment by ilker-aktuna** [comment]
```
~ # opkg install coreutils-nohup
Installing coreutils-nohup (9.3-1) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/coreutils-nohup_9.3-1_mipsel-3.4.ipk
Configuring coreutils-nohup.
~ # nohup 
nohup: missing operand
Try 'nohup --help' for more information.
~ # 
```
so "coreutils-nohup" package is required
